import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import logoDark from "../public/images/logo-flat-dark.svg";
import logoLight from "../public/images/logo-flat-light.svg";
import { ChangeColorProvider } from "./Components/ChangeColorProvider";
import NavBar from "./Components/NavBar";
import "./globals.css";

const poppins = Poppins({ weight: ["400", "500", "600", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Devsitter",
    description: "Generated by create next app",
    icons: [
        {
            rel: "icon",
            type: "image/x-icon",
            url: logoDark.src,
            media: "(prefers-color-scheme: light)",
        },
        {
            rel: "icon",
            type: "image/x-icon",
            url: logoLight.src,
            media: "(prefers-color-scheme: dark)",
        },
    ],
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={poppins.className}>
                <ChangeColorProvider>
                    <NavBar></NavBar>
                    <main>{children}</main>
                </ChangeColorProvider>
            </body>
        </html>
    );
}
